name: base
channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base
  - r-epitools
  - rpy2
  - r-irkernel
  - r-plotly
  - r-knitr
  - r-shiny
  - r-ggplot2
  - r-devtools
  - r-dplyr
  - r-dt
  - r-pkgbuild
  - gxx_linux-64
  - python
  - notebook
  - nbconvert
  - jupyter_contrib_nbextensions
  - xlrd
  - bcftools
  - samtools
  - vcftools
  - htslib
  - bwa
  - bowtie2
  - primer3
  - primer3-py
  - numpy
  - scipy
  - biopython
  - pysam
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scandir
  - openpyxl
  - simplegeneric
  - matplotlib-venn
  - tblib
  - parallel
  - scikit-allel
  - bioconductor-dnacopy
  - basemap-data-hires
  - seqtk=1.3
  - gatk4
  - freebayes
  - lastz
  - plotly
  - texlive-core
  - libgfortran4
prefix: /opt/conda
