name: base
channels:
  - conda-forge
  - bioconda
  - r
  - nodefaults
dependencies:
  - basemap-data-hires
  - bcftools
  - bioconductor-dnacopy
  - biopython
  - bowtie2
  - bwa
  - freebayes
  - gatk4
  - gxx_linux-64
  - htslib
  - jupyter_contrib_nbextensions
  - lastz
  - matplotlib
  - matplotlib-venn
  - nbconvert
  - notebook
  - numpy
  - openpyxl
  - pandas
  - parallel
  - pip
  - pip:
      - mipscripts
  - plotly
  - plotnine
  - primer3
  - primer3-py
  - pysam
  - python
  - r-base
  - r-devtools
  - r-dplyr
  - r-dt
  - r-epitools
  - r-ggplot2
  - r-irkernel
  - r-knitr
  - r-pkgbuild
  - r-plotly
  - r-shiny
  - rpy2
  - samtools
  - scandir
  - scikit-allel
  - scikit-learn
  - scipy
  - seaborn
  - seqtk=1.3
  - simplegeneric
  - tblib
  - texlive-core
  - vcftools
  - xlrd
prefix: /opt/conda
